before_script:
  - docker version
  - docker-compose version
  - docker network inspect saokanneh

build:
  script:
    - source .env
    - ./mvnw install
  stage: build
  only:
    refs:
      - master
  tags:
    - build

deploy:
  script:
    - source .env
    - docker-compose up -d
  stage: deploy
  only:
    refs:
      - master
  tags:
    - deploy

