before_script:
  - docker version
  - docker-compose version

deploy:
  script:
    - source .env
    - docker-compose up -d
  stage: deploy
  only:
    refs:
      - master
  tags:
    - deploy
