version: 0.0
os: linux
files:
  - source: /
  - destination: /var/www/spring_app
artifacts:
  files:
    - appspec.yml
    - docker-compose.yml
    - Dockerfile
    - target/mobile-app-ws-0.1.jar
    - scripts/*

hooks:
  ApplicationStart:
    - location: scripts/start.sh
      runas: root