version: 0.2
phases:
  build:
    commands:
      - ./mvnw install -DskipTests
artifacts:
  files:
    - target/mobile-app-ws-0.1.jar
    - appspec.yml
    - docker-compose.yml
    - Dockerfile
    - scripts/*
cache:
  paths:
    - 'target/*'