version: "3.6"
volumes:
  app_vol:

networks:
  default:
    external: true
    name: saokanneh

services:
  udemy_spring_app:
    container_name: udemy_spring_app
    build:
      args:
        DB_ENV_NAME: ${DB_ENV_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - 8080
    environment:
      - VIRTUAL_HOST=spring.saokanneh.com
      - VIRTUAL_PORT=8080
      - DB_ENV_NAME
      - DB_USER
      - DB_PASS
    external_links:
      - spring_app_db:spring_app_db
