version: "3.6"
volumes:
  app_vol:

networks:
  saokanneh:
    external: true
    name: saokanneh

services:
  udemy_spring_app:
    container_name: udemy_spring_app
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - "8080"
    environment:
      - VIRTUAL_HOST=spring_app.saokanneh.com
      - VIRTUAL_PORT=8080
      - DB_ENV_NAME=spring_app_db
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    links:
      - mysql
    networks:
      - saokanneh
