version: "3.6"
volumes:
  app_vol:

networks:
  saokanneh:
    driver: bridge
    external: true
    name: saokanneh

services:
  udemy_spring_app:
    container_name: udemy_spring_app
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - saokanneh
    expose:
      - 8080
    environment:
      - VIRTUAL_HOST=spring.saokanneh.com
      - DB_ENV_NAME
      - DB_USER
      - DB_PASS
    external_links:
      - spring_app_db:spring_app_db
      - nginx-proxy:nginx-proxy
